USE DBRENDAFIXA
GO

	BEGIN TRAN

	DELETE [PI]
	  FROM POSICAOIMPOSTO [PI]
	  JOIN POSICAO P
	    ON PI.ID_INVESTIMENTO = P.ID_INVESTIMENTO
	   AND PI.CD_INVESTIMENTO = P.CD_INVESTIMENTO
	   AND PI.ID_POSICAO = P.ID_POSICAO
     WHERE P.DT_POSICAO = CAST (GETDATE() AS DATE)

	DELETE POSICAO WHERE DT_POSICAO = CAST (GETDATE() AS DATE)

	 --COMMIT